name: Release to GitHub Maven

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.X_GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Remove -SNAPSHOT from version
        run: |
          sed -i '0,/-SNAPSHOT/s// /' pom.xml
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add pom.xml
          git commit -m "Release version $(grep -m1 '<version>' pom.xml | sed -E 's/.*<version>([0-9]+\.[0-9]+\.[0-9]+)<.*<\/version>.*/\1/')"

      - name: Deploy release to GitHub Packages
        run: mvn deploy -B --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.X_GITHUB_TOKEN }}

      - name: Bump version
        run: |
          VERSION=$(grep -m1 '<version>' pom.xml | sed -E 's/.*<version>([0-9]+)\.([0-9]+)\.([0-9]+)<.*<\/version>.*/\1 \2 \3/')
          MAJOR=$(echo $VERSION | cut -d' ' -f1)
          MINOR=$(echo $VERSION | cut -d' ' -f2)
          # Always reset PATCH to 0 and bump MINOR
          NEW_MINOR=$((MINOR+1))
          sed -i "0,/<version>[0-9]\+\.[0-9]\+\.[0-9]\+<\/version>/s//<version>${MAJOR}.${NEW_MINOR}.0-SNAPSHOT<\/version>/" pom.xml
          git add pom.xml
          git commit -m "Bump version to ${MAJOR}.${NEW_MINOR}.0-SNAPSHOT"
          git push
