name: Release to GitHub Maven

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Set Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # 1. Remove -SNAPSHOT
      - name: Prepare release version
        id: version
        run: |
          VERSION=$(grep -m1 '<version>' pom.xml | sed -nE 's/.*<version>(.*)-SNAPSHOT<\/version>/\1/p')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          sed -i "0,/-SNAPSHOT<\/version>/s/-SNAPSHOT<\/version>/<\/version>/" pom.xml

          git add pom.xml
          git commit -m "Release version $VERSION"

      # 2. Create tag
      - name: Create tag
        run: |
          git tag v${{ steps.version.outputs.version }}
          git push origin v${{ steps.version.outputs.version }}

      # 3. Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4. Deploy Maven package
      - name: Deploy to GitHub Packages
        run: mvn deploy --settings .github/settings.xml -B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      # 5. Bump version
      - name: Bump to next SNAPSHOT
        run: |
          VERSION=${{ steps.version.outputs.version }}
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)

          NEW_MINOR=$((MINOR+1))

          NEW_VERSION="${MAJOR}.${NEW_MINOR}.0-SNAPSHOT"

          sed -i "0,/<version>.*<\/version>/s//<version>${NEW_VERSION}<\/version>/" pom.xml

          git add pom.xml
          git commit -m "Release $VERSION and Bump version to ${NEW_VERSION}"
          git push